package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LaoFang;
import org.linlinjava.litemall.db.domain.example.LaoFangExample;

public interface LaoFangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    long countByExample(LaoFangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int deleteByExample(LaoFangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int insert(LaoFang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int insertSelective(LaoFang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    List<LaoFang> selectByExample(LaoFangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    LaoFang selectByPrimaryKey(Integer id);
    LaoFang selectOneByExample(LaoFangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") LaoFang record, @Param("example") LaoFangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByExample(@Param("record") LaoFang record, @Param("example") LaoFangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByPrimaryKeySelective(LaoFang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lao_fang
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByPrimaryKey(LaoFang record);
}