package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.Party;
import org.linlinjava.litemall.db.domain.PartyExample;

public interface PartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    long countByExample(PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int deleteByExample(PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int insert(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int insertSelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    List<Party> selectByExample(PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    Party selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") Party record, @Param("example") PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int updateByExample(@Param("record") Party record, @Param("example") PartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int updateByPrimaryKeySelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table party
     *
     * @mbg.generated Tue Jan 21 16:59:54 CST 2020
     */
    int updateByPrimaryKey(Party record);
}