package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.PKRecord;
import org.linlinjava.litemall.db.domain.example.PKRecordExample;

public interface PKRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    long countByExample(PKRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int deleteByExample(PKRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int insert(PKRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int insertSelective(PKRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    List<PKRecord> selectByExample(PKRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    PKRecord selectByPrimaryKey(Integer id);
    PKRecord selectOneByExample(PKRecordExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") PKRecord record, @Param("example") PKRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByExample(@Param("record") PKRecord record, @Param("example") PKRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByPrimaryKeySelective(PKRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    int updateByPrimaryKey(PKRecord record);
}