package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.ShangGuYaoWangInfo;
import org.linlinjava.litemall.db.domain.example.ShangGuYaoWangInfoExample;

public interface ShangGuYaoWangInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    long countByExample(ShangGuYaoWangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int deleteByExample(ShangGuYaoWangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int insert(ShangGuYaoWangInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int insertSelective(ShangGuYaoWangInfo record);

    ShangGuYaoWangInfo selectOneByExample(ShangGuYaoWangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    List<ShangGuYaoWangInfo> selectByExample(ShangGuYaoWangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    ShangGuYaoWangInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") ShangGuYaoWangInfo record, @Param("example") ShangGuYaoWangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int updateByExample(@Param("record") ShangGuYaoWangInfo record, @Param("example") ShangGuYaoWangInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int updateByPrimaryKeySelective(ShangGuYaoWangInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shang_gu_yao_wang_info
     *
     * @mbg.generated Sat Jan 11 20:37:28 CST 2020
     */
    int updateByPrimaryKey(ShangGuYaoWangInfo record);
}