package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.T_FightObject;
import org.linlinjava.litemall.db.domain.T_FightObjectExample;

public interface T_FightObjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    long countByExample(T_FightObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int deleteByExample(T_FightObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int insert(T_FightObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int insertSelective(T_FightObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    List<T_FightObject> selectByExample(T_FightObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    T_FightObject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") T_FightObject record, @Param("example") T_FightObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByExample(@Param("record") T_FightObject record, @Param("example") T_FightObjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByPrimaryKeySelective(T_FightObject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fight_object
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByPrimaryKey(T_FightObject record);
}