package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.T_Pet_INTIMACY;
import org.linlinjava.litemall.db.domain.T_Pet_INTIMACYExample;

public interface T_Pet_INTIMACYMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    long countByExample(T_Pet_INTIMACYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int deleteByExample(T_Pet_INTIMACYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int insert(T_Pet_INTIMACY record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int insertSelective(T_Pet_INTIMACY record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    List<T_Pet_INTIMACY> selectByExample(T_Pet_INTIMACYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    T_Pet_INTIMACY selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") T_Pet_INTIMACY record, @Param("example") T_Pet_INTIMACYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int updateByExample(@Param("record") T_Pet_INTIMACY record, @Param("example") T_Pet_INTIMACYExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int updateByPrimaryKeySelective(T_Pet_INTIMACY record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    int updateByPrimaryKey(T_Pet_INTIMACY record);
}