package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.UserPartyShop;
import org.linlinjava.litemall.db.domain.UserPartyShopExample;

public interface UserPartyShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    long countByExample(UserPartyShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int deleteByExample(UserPartyShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int insert(UserPartyShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int insertSelective(UserPartyShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    List<UserPartyShop> selectByExample(UserPartyShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    UserPartyShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPartyShop record, @Param("example") UserPartyShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int updateByExample(@Param("record") UserPartyShop record, @Param("example") UserPartyShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int updateByPrimaryKeySelective(UserPartyShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    int updateByPrimaryKey(UserPartyShop record);
}