package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.UserParty;
import org.linlinjava.litemall.db.domain.UserPartyExample;

public interface UserPartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    long countByExample(UserPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int deleteByExample(UserPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int insert(UserParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int insertSelective(UserParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    List<UserParty> selectByExample(UserPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    UserParty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserParty record, @Param("example") UserPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByExample(@Param("record") UserParty record, @Param("example") UserPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByPrimaryKeySelective(UserParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    int updateByPrimaryKey(UserParty record);
}