spring:
  profiles:
    active: db, core,  wx, gameserver
  messages:
    encoding: UTF-8

server:
  http:
    port: 81
  port: 81
  tomcat:
    max-threads: 3000


logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.core:  DEBUG
    org.linlinjava.litemall.gameserver: DEBUG
  path: ./logs/
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'


netty:
  port: 14721
  url: 0.0.0.0
  ip: 117.24.6.15

serverId: 1