package org.linlinjava.litemall.db.domain;

public class PKRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.pk_chara_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private Integer pkCharaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.be_pk_chara_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private Integer bePkCharaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.server_name
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private String serverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.server_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private String serverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.win_state
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private Boolean winState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.add_time
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private String addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pk_record.update_time
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public PKRecord(Integer id, Integer pkCharaId, Integer bePkCharaId, String serverName, String serverId, Boolean winState, String addTime, String updateTime) {
        this.id = id;
        this.pkCharaId = pkCharaId;
        this.bePkCharaId = bePkCharaId;
        this.serverName = serverName;
        this.serverId = serverId;
        this.winState = winState;
        this.addTime = addTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public PKRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.id
     *
     * @return the value of pk_record.id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.id
     *
     * @param id the value for pk_record.id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.pk_chara_id
     *
     * @return the value of pk_record.pk_chara_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public Integer getPkCharaId() {
        return pkCharaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.pk_chara_id
     *
     * @param pkCharaId the value for pk_record.pk_chara_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setPkCharaId(Integer pkCharaId) {
        this.pkCharaId = pkCharaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.be_pk_chara_id
     *
     * @return the value of pk_record.be_pk_chara_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public Integer getBePkCharaId() {
        return bePkCharaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.be_pk_chara_id
     *
     * @param bePkCharaId the value for pk_record.be_pk_chara_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setBePkCharaId(Integer bePkCharaId) {
        this.bePkCharaId = bePkCharaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.server_name
     *
     * @return the value of pk_record.server_name
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.server_name
     *
     * @param serverName the value for pk_record.server_name
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setServerName(String serverName) {
        this.serverName = serverName == null ? null : serverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.server_id
     *
     * @return the value of pk_record.server_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.server_id
     *
     * @param serverId the value for pk_record.server_id
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setServerId(String serverId) {
        this.serverId = serverId == null ? null : serverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.win_state
     *
     * @return the value of pk_record.win_state
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public Boolean getWinState() {
        return winState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.win_state
     *
     * @param winState the value for pk_record.win_state
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setWinState(Boolean winState) {
        this.winState = winState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.add_time
     *
     * @return the value of pk_record.add_time
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.add_time
     *
     * @param addTime the value for pk_record.add_time
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pk_record.update_time
     *
     * @return the value of pk_record.update_time
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pk_record.update_time
     *
     * @param updateTime the value for pk_record.update_time
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}