package org.linlinjava.litemall.db.domain;

public class T_Pet_INTIMACY {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.id
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.name
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.intimacy_begin
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer intimacyBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.intimacy_end
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer intimacyEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.revive_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer revivePer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.revive_num
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer reviveNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.conti_hit_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer contiHitPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.conti_hit_num
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer contiHitNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.hit_kill_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer hitKillPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.attack_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer attackPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet_intimacy.defence_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    private Integer defencePer;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public T_Pet_INTIMACY(Integer id, String name, Integer intimacyBegin, Integer intimacyEnd, Integer revivePer, Integer reviveNum, Integer contiHitPer, Integer contiHitNum, Integer hitKillPer, Integer attackPer, Integer defencePer) {
        this.id = id;
        this.name = name;
        this.intimacyBegin = intimacyBegin;
        this.intimacyEnd = intimacyEnd;
        this.revivePer = revivePer;
        this.reviveNum = reviveNum;
        this.contiHitPer = contiHitPer;
        this.contiHitNum = contiHitNum;
        this.hitKillPer = hitKillPer;
        this.attackPer = attackPer;
        this.defencePer = defencePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public T_Pet_INTIMACY() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.id
     *
     * @return the value of t_pet_intimacy.id
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.id
     *
     * @param id the value for t_pet_intimacy.id
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.name
     *
     * @return the value of t_pet_intimacy.name
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.name
     *
     * @param name the value for t_pet_intimacy.name
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.intimacy_begin
     *
     * @return the value of t_pet_intimacy.intimacy_begin
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getIntimacyBegin() {
        return intimacyBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.intimacy_begin
     *
     * @param intimacyBegin the value for t_pet_intimacy.intimacy_begin
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setIntimacyBegin(Integer intimacyBegin) {
        this.intimacyBegin = intimacyBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.intimacy_end
     *
     * @return the value of t_pet_intimacy.intimacy_end
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getIntimacyEnd() {
        return intimacyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.intimacy_end
     *
     * @param intimacyEnd the value for t_pet_intimacy.intimacy_end
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setIntimacyEnd(Integer intimacyEnd) {
        this.intimacyEnd = intimacyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.revive_per
     *
     * @return the value of t_pet_intimacy.revive_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getRevivePer() {
        return revivePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.revive_per
     *
     * @param revivePer the value for t_pet_intimacy.revive_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setRevivePer(Integer revivePer) {
        this.revivePer = revivePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.revive_num
     *
     * @return the value of t_pet_intimacy.revive_num
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getReviveNum() {
        return reviveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.revive_num
     *
     * @param reviveNum the value for t_pet_intimacy.revive_num
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setReviveNum(Integer reviveNum) {
        this.reviveNum = reviveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.conti_hit_per
     *
     * @return the value of t_pet_intimacy.conti_hit_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getContiHitPer() {
        return contiHitPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.conti_hit_per
     *
     * @param contiHitPer the value for t_pet_intimacy.conti_hit_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setContiHitPer(Integer contiHitPer) {
        this.contiHitPer = contiHitPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.conti_hit_num
     *
     * @return the value of t_pet_intimacy.conti_hit_num
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getContiHitNum() {
        return contiHitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.conti_hit_num
     *
     * @param contiHitNum the value for t_pet_intimacy.conti_hit_num
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setContiHitNum(Integer contiHitNum) {
        this.contiHitNum = contiHitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.hit_kill_per
     *
     * @return the value of t_pet_intimacy.hit_kill_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getHitKillPer() {
        return hitKillPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.hit_kill_per
     *
     * @param hitKillPer the value for t_pet_intimacy.hit_kill_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setHitKillPer(Integer hitKillPer) {
        this.hitKillPer = hitKillPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.attack_per
     *
     * @return the value of t_pet_intimacy.attack_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getAttackPer() {
        return attackPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.attack_per
     *
     * @param attackPer the value for t_pet_intimacy.attack_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setAttackPer(Integer attackPer) {
        this.attackPer = attackPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet_intimacy.defence_per
     *
     * @return the value of t_pet_intimacy.defence_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Integer getDefencePer() {
        return defencePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet_intimacy.defence_per
     *
     * @param defencePer the value for t_pet_intimacy.defence_per
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setDefencePer(Integer defencePer) {
        this.defencePer = defencePer;
    }
}