package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.List;

public class T_Pet_INTIMACYExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public T_Pet_INTIMACYExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginIsNull() {
            addCriterion("intimacy_begin is null");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginIsNotNull() {
            addCriterion("intimacy_begin is not null");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginEqualTo(Integer value) {
            addCriterion("intimacy_begin =", value, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginNotEqualTo(Integer value) {
            addCriterion("intimacy_begin <>", value, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginGreaterThan(Integer value) {
            addCriterion("intimacy_begin >", value, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginGreaterThanOrEqualTo(Integer value) {
            addCriterion("intimacy_begin >=", value, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginLessThan(Integer value) {
            addCriterion("intimacy_begin <", value, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginLessThanOrEqualTo(Integer value) {
            addCriterion("intimacy_begin <=", value, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginIn(List<Integer> values) {
            addCriterion("intimacy_begin in", values, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginNotIn(List<Integer> values) {
            addCriterion("intimacy_begin not in", values, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginBetween(Integer value1, Integer value2) {
            addCriterion("intimacy_begin between", value1, value2, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyBeginNotBetween(Integer value1, Integer value2) {
            addCriterion("intimacy_begin not between", value1, value2, "intimacyBegin");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndIsNull() {
            addCriterion("intimacy_end is null");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndIsNotNull() {
            addCriterion("intimacy_end is not null");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndEqualTo(Integer value) {
            addCriterion("intimacy_end =", value, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndNotEqualTo(Integer value) {
            addCriterion("intimacy_end <>", value, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndGreaterThan(Integer value) {
            addCriterion("intimacy_end >", value, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndGreaterThanOrEqualTo(Integer value) {
            addCriterion("intimacy_end >=", value, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndLessThan(Integer value) {
            addCriterion("intimacy_end <", value, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndLessThanOrEqualTo(Integer value) {
            addCriterion("intimacy_end <=", value, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndIn(List<Integer> values) {
            addCriterion("intimacy_end in", values, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndNotIn(List<Integer> values) {
            addCriterion("intimacy_end not in", values, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndBetween(Integer value1, Integer value2) {
            addCriterion("intimacy_end between", value1, value2, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andIntimacyEndNotBetween(Integer value1, Integer value2) {
            addCriterion("intimacy_end not between", value1, value2, "intimacyEnd");
            return (Criteria) this;
        }

        public Criteria andRevivePerIsNull() {
            addCriterion("revive_per is null");
            return (Criteria) this;
        }

        public Criteria andRevivePerIsNotNull() {
            addCriterion("revive_per is not null");
            return (Criteria) this;
        }

        public Criteria andRevivePerEqualTo(Integer value) {
            addCriterion("revive_per =", value, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerNotEqualTo(Integer value) {
            addCriterion("revive_per <>", value, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerGreaterThan(Integer value) {
            addCriterion("revive_per >", value, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerGreaterThanOrEqualTo(Integer value) {
            addCriterion("revive_per >=", value, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerLessThan(Integer value) {
            addCriterion("revive_per <", value, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerLessThanOrEqualTo(Integer value) {
            addCriterion("revive_per <=", value, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerIn(List<Integer> values) {
            addCriterion("revive_per in", values, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerNotIn(List<Integer> values) {
            addCriterion("revive_per not in", values, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerBetween(Integer value1, Integer value2) {
            addCriterion("revive_per between", value1, value2, "revivePer");
            return (Criteria) this;
        }

        public Criteria andRevivePerNotBetween(Integer value1, Integer value2) {
            addCriterion("revive_per not between", value1, value2, "revivePer");
            return (Criteria) this;
        }

        public Criteria andReviveNumIsNull() {
            addCriterion("revive_num is null");
            return (Criteria) this;
        }

        public Criteria andReviveNumIsNotNull() {
            addCriterion("revive_num is not null");
            return (Criteria) this;
        }

        public Criteria andReviveNumEqualTo(Integer value) {
            addCriterion("revive_num =", value, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumNotEqualTo(Integer value) {
            addCriterion("revive_num <>", value, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumGreaterThan(Integer value) {
            addCriterion("revive_num >", value, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("revive_num >=", value, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumLessThan(Integer value) {
            addCriterion("revive_num <", value, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumLessThanOrEqualTo(Integer value) {
            addCriterion("revive_num <=", value, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumIn(List<Integer> values) {
            addCriterion("revive_num in", values, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumNotIn(List<Integer> values) {
            addCriterion("revive_num not in", values, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumBetween(Integer value1, Integer value2) {
            addCriterion("revive_num between", value1, value2, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andReviveNumNotBetween(Integer value1, Integer value2) {
            addCriterion("revive_num not between", value1, value2, "reviveNum");
            return (Criteria) this;
        }

        public Criteria andContiHitPerIsNull() {
            addCriterion("conti_hit_per is null");
            return (Criteria) this;
        }

        public Criteria andContiHitPerIsNotNull() {
            addCriterion("conti_hit_per is not null");
            return (Criteria) this;
        }

        public Criteria andContiHitPerEqualTo(Integer value) {
            addCriterion("conti_hit_per =", value, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerNotEqualTo(Integer value) {
            addCriterion("conti_hit_per <>", value, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerGreaterThan(Integer value) {
            addCriterion("conti_hit_per >", value, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerGreaterThanOrEqualTo(Integer value) {
            addCriterion("conti_hit_per >=", value, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerLessThan(Integer value) {
            addCriterion("conti_hit_per <", value, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerLessThanOrEqualTo(Integer value) {
            addCriterion("conti_hit_per <=", value, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerIn(List<Integer> values) {
            addCriterion("conti_hit_per in", values, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerNotIn(List<Integer> values) {
            addCriterion("conti_hit_per not in", values, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerBetween(Integer value1, Integer value2) {
            addCriterion("conti_hit_per between", value1, value2, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitPerNotBetween(Integer value1, Integer value2) {
            addCriterion("conti_hit_per not between", value1, value2, "contiHitPer");
            return (Criteria) this;
        }

        public Criteria andContiHitNumIsNull() {
            addCriterion("conti_hit_num is null");
            return (Criteria) this;
        }

        public Criteria andContiHitNumIsNotNull() {
            addCriterion("conti_hit_num is not null");
            return (Criteria) this;
        }

        public Criteria andContiHitNumEqualTo(Integer value) {
            addCriterion("conti_hit_num =", value, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumNotEqualTo(Integer value) {
            addCriterion("conti_hit_num <>", value, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumGreaterThan(Integer value) {
            addCriterion("conti_hit_num >", value, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("conti_hit_num >=", value, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumLessThan(Integer value) {
            addCriterion("conti_hit_num <", value, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumLessThanOrEqualTo(Integer value) {
            addCriterion("conti_hit_num <=", value, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumIn(List<Integer> values) {
            addCriterion("conti_hit_num in", values, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumNotIn(List<Integer> values) {
            addCriterion("conti_hit_num not in", values, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumBetween(Integer value1, Integer value2) {
            addCriterion("conti_hit_num between", value1, value2, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andContiHitNumNotBetween(Integer value1, Integer value2) {
            addCriterion("conti_hit_num not between", value1, value2, "contiHitNum");
            return (Criteria) this;
        }

        public Criteria andHitKillPerIsNull() {
            addCriterion("hit_kill_per is null");
            return (Criteria) this;
        }

        public Criteria andHitKillPerIsNotNull() {
            addCriterion("hit_kill_per is not null");
            return (Criteria) this;
        }

        public Criteria andHitKillPerEqualTo(Integer value) {
            addCriterion("hit_kill_per =", value, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerNotEqualTo(Integer value) {
            addCriterion("hit_kill_per <>", value, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerGreaterThan(Integer value) {
            addCriterion("hit_kill_per >", value, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerGreaterThanOrEqualTo(Integer value) {
            addCriterion("hit_kill_per >=", value, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerLessThan(Integer value) {
            addCriterion("hit_kill_per <", value, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerLessThanOrEqualTo(Integer value) {
            addCriterion("hit_kill_per <=", value, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerIn(List<Integer> values) {
            addCriterion("hit_kill_per in", values, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerNotIn(List<Integer> values) {
            addCriterion("hit_kill_per not in", values, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerBetween(Integer value1, Integer value2) {
            addCriterion("hit_kill_per between", value1, value2, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andHitKillPerNotBetween(Integer value1, Integer value2) {
            addCriterion("hit_kill_per not between", value1, value2, "hitKillPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerIsNull() {
            addCriterion("attack_per is null");
            return (Criteria) this;
        }

        public Criteria andAttackPerIsNotNull() {
            addCriterion("attack_per is not null");
            return (Criteria) this;
        }

        public Criteria andAttackPerEqualTo(Integer value) {
            addCriterion("attack_per =", value, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerNotEqualTo(Integer value) {
            addCriterion("attack_per <>", value, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerGreaterThan(Integer value) {
            addCriterion("attack_per >", value, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerGreaterThanOrEqualTo(Integer value) {
            addCriterion("attack_per >=", value, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerLessThan(Integer value) {
            addCriterion("attack_per <", value, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerLessThanOrEqualTo(Integer value) {
            addCriterion("attack_per <=", value, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerIn(List<Integer> values) {
            addCriterion("attack_per in", values, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerNotIn(List<Integer> values) {
            addCriterion("attack_per not in", values, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerBetween(Integer value1, Integer value2) {
            addCriterion("attack_per between", value1, value2, "attackPer");
            return (Criteria) this;
        }

        public Criteria andAttackPerNotBetween(Integer value1, Integer value2) {
            addCriterion("attack_per not between", value1, value2, "attackPer");
            return (Criteria) this;
        }

        public Criteria andDefencePerIsNull() {
            addCriterion("defence_per is null");
            return (Criteria) this;
        }

        public Criteria andDefencePerIsNotNull() {
            addCriterion("defence_per is not null");
            return (Criteria) this;
        }

        public Criteria andDefencePerEqualTo(Integer value) {
            addCriterion("defence_per =", value, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerNotEqualTo(Integer value) {
            addCriterion("defence_per <>", value, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerGreaterThan(Integer value) {
            addCriterion("defence_per >", value, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerGreaterThanOrEqualTo(Integer value) {
            addCriterion("defence_per >=", value, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerLessThan(Integer value) {
            addCriterion("defence_per <", value, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerLessThanOrEqualTo(Integer value) {
            addCriterion("defence_per <=", value, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerIn(List<Integer> values) {
            addCriterion("defence_per in", values, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerNotIn(List<Integer> values) {
            addCriterion("defence_per not in", values, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerBetween(Integer value1, Integer value2) {
            addCriterion("defence_per between", value1, value2, "defencePer");
            return (Criteria) this;
        }

        public Criteria andDefencePerNotBetween(Integer value1, Integer value2) {
            addCriterion("defence_per not between", value1, value2, "defencePer");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 19 17:07:53 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pet_intimacy
     *
     * @mbg.generated Sun Jan 19 17:07:53 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}