package org.linlinjava.litemall.db.domain;

public class UserPartyShop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_party_shop.id
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_party_shop.data
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public UserPartyShop(Integer id, String data) {
        this.id = id;
        this.data = data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_shop
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public UserPartyShop() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_party_shop.id
     *
     * @return the value of user_party_shop.id
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_party_shop.id
     *
     * @param id the value for user_party_shop.id
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_party_shop.data
     *
     * @return the value of user_party_shop.data
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_party_shop.data
     *
     * @param data the value for user_party_shop.data
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}