package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.List;

public class UserPartyDailyTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public UserPartyDailyTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdIsNull() {
            addCriterion("cur_task_id is null");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdIsNotNull() {
            addCriterion("cur_task_id is not null");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdEqualTo(Integer value) {
            addCriterion("cur_task_id =", value, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdNotEqualTo(Integer value) {
            addCriterion("cur_task_id <>", value, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdGreaterThan(Integer value) {
            addCriterion("cur_task_id >", value, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cur_task_id >=", value, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdLessThan(Integer value) {
            addCriterion("cur_task_id <", value, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("cur_task_id <=", value, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdIn(List<Integer> values) {
            addCriterion("cur_task_id in", values, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdNotIn(List<Integer> values) {
            addCriterion("cur_task_id not in", values, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("cur_task_id between", value1, value2, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cur_task_id not between", value1, value2, "curTaskId");
            return (Criteria) this;
        }

        public Criteria andCurProcessIsNull() {
            addCriterion("cur_process is null");
            return (Criteria) this;
        }

        public Criteria andCurProcessIsNotNull() {
            addCriterion("cur_process is not null");
            return (Criteria) this;
        }

        public Criteria andCurProcessEqualTo(Integer value) {
            addCriterion("cur_process =", value, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessNotEqualTo(Integer value) {
            addCriterion("cur_process <>", value, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessGreaterThan(Integer value) {
            addCriterion("cur_process >", value, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessGreaterThanOrEqualTo(Integer value) {
            addCriterion("cur_process >=", value, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessLessThan(Integer value) {
            addCriterion("cur_process <", value, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessLessThanOrEqualTo(Integer value) {
            addCriterion("cur_process <=", value, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessIn(List<Integer> values) {
            addCriterion("cur_process in", values, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessNotIn(List<Integer> values) {
            addCriterion("cur_process not in", values, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessBetween(Integer value1, Integer value2) {
            addCriterion("cur_process between", value1, value2, "curProcess");
            return (Criteria) this;
        }

        public Criteria andCurProcessNotBetween(Integer value1, Integer value2) {
            addCriterion("cur_process not between", value1, value2, "curProcess");
            return (Criteria) this;
        }

        public Criteria andDayNoIsNull() {
            addCriterion("day_no is null");
            return (Criteria) this;
        }

        public Criteria andDayNoIsNotNull() {
            addCriterion("day_no is not null");
            return (Criteria) this;
        }

        public Criteria andDayNoEqualTo(Integer value) {
            addCriterion("day_no =", value, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoNotEqualTo(Integer value) {
            addCriterion("day_no <>", value, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoGreaterThan(Integer value) {
            addCriterion("day_no >", value, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("day_no >=", value, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoLessThan(Integer value) {
            addCriterion("day_no <", value, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoLessThanOrEqualTo(Integer value) {
            addCriterion("day_no <=", value, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoIn(List<Integer> values) {
            addCriterion("day_no in", values, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoNotIn(List<Integer> values) {
            addCriterion("day_no not in", values, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoBetween(Integer value1, Integer value2) {
            addCriterion("day_no between", value1, value2, "dayNo");
            return (Criteria) this;
        }

        public Criteria andDayNoNotBetween(Integer value1, Integer value2) {
            addCriterion("day_no not between", value1, value2, "dayNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_party_daily_task
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 09 22:55:27 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Thu Jan 09 22:55:27 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}