package org.linlinjava.litemall.db.domain;

public class UserPartyDailyTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_party_daily_task.id
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_party_daily_task.cur_task_id
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    private Integer curTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_party_daily_task.cur_process
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    private Integer curProcess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_party_daily_task.day_no
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    private Integer dayNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public UserPartyDailyTask(Integer id, Integer curTaskId, Integer curProcess, Integer dayNo) {
        this.id = id;
        this.curTaskId = curTaskId;
        this.curProcess = curProcess;
        this.dayNo = dayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party_daily_task
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public UserPartyDailyTask() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_party_daily_task.id
     *
     * @return the value of user_party_daily_task.id
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_party_daily_task.id
     *
     * @param id the value for user_party_daily_task.id
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_party_daily_task.cur_task_id
     *
     * @return the value of user_party_daily_task.cur_task_id
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public Integer getCurTaskId() {
        return curTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_party_daily_task.cur_task_id
     *
     * @param curTaskId the value for user_party_daily_task.cur_task_id
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void setCurTaskId(Integer curTaskId) {
        this.curTaskId = curTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_party_daily_task.cur_process
     *
     * @return the value of user_party_daily_task.cur_process
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public Integer getCurProcess() {
        return curProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_party_daily_task.cur_process
     *
     * @param curProcess the value for user_party_daily_task.cur_process
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void setCurProcess(Integer curProcess) {
        this.curProcess = curProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_party_daily_task.day_no
     *
     * @return the value of user_party_daily_task.day_no
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public Integer getDayNo() {
        return dayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_party_daily_task.day_no
     *
     * @param dayNo the value for user_party_daily_task.day_no
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void setDayNo(Integer dayNo) {
        this.dayNo = dayNo;
    }
}