package org.linlinjava.litemall.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserPartyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public UserPartyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPartyidIsNull() {
            addCriterion("partyId is null");
            return (Criteria) this;
        }

        public Criteria andPartyidIsNotNull() {
            addCriterion("partyId is not null");
            return (Criteria) this;
        }

        public Criteria andPartyidEqualTo(Integer value) {
            addCriterion("partyId =", value, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidNotEqualTo(Integer value) {
            addCriterion("partyId <>", value, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidGreaterThan(Integer value) {
            addCriterion("partyId >", value, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("partyId >=", value, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidLessThan(Integer value) {
            addCriterion("partyId <", value, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidLessThanOrEqualTo(Integer value) {
            addCriterion("partyId <=", value, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidIn(List<Integer> values) {
            addCriterion("partyId in", values, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidNotIn(List<Integer> values) {
            addCriterion("partyId not in", values, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidBetween(Integer value1, Integer value2) {
            addCriterion("partyId between", value1, value2, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartyidNotBetween(Integer value1, Integer value2) {
            addCriterion("partyId not between", value1, value2, "partyid");
            return (Criteria) this;
        }

        public Criteria andPartynameIsNull() {
            addCriterion("partyName is null");
            return (Criteria) this;
        }

        public Criteria andPartynameIsNotNull() {
            addCriterion("partyName is not null");
            return (Criteria) this;
        }

        public Criteria andPartynameEqualTo(String value) {
            addCriterion("partyName =", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameNotEqualTo(String value) {
            addCriterion("partyName <>", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameGreaterThan(String value) {
            addCriterion("partyName >", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameGreaterThanOrEqualTo(String value) {
            addCriterion("partyName >=", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameLessThan(String value) {
            addCriterion("partyName <", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameLessThanOrEqualTo(String value) {
            addCriterion("partyName <=", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameLike(String value) {
            addCriterion("partyName like", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameNotLike(String value) {
            addCriterion("partyName not like", value, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameIn(List<String> values) {
            addCriterion("partyName in", values, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameNotIn(List<String> values) {
            addCriterion("partyName not in", values, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameBetween(String value1, String value2) {
            addCriterion("partyName between", value1, value2, "partyname");
            return (Criteria) this;
        }

        public Criteria andPartynameNotBetween(String value1, String value2) {
            addCriterion("partyName not between", value1, value2, "partyname");
            return (Criteria) this;
        }

        public Criteria andContribIsNull() {
            addCriterion("contrib is null");
            return (Criteria) this;
        }

        public Criteria andContribIsNotNull() {
            addCriterion("contrib is not null");
            return (Criteria) this;
        }

        public Criteria andContribEqualTo(Integer value) {
            addCriterion("contrib =", value, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribNotEqualTo(Integer value) {
            addCriterion("contrib <>", value, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribGreaterThan(Integer value) {
            addCriterion("contrib >", value, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribGreaterThanOrEqualTo(Integer value) {
            addCriterion("contrib >=", value, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribLessThan(Integer value) {
            addCriterion("contrib <", value, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribLessThanOrEqualTo(Integer value) {
            addCriterion("contrib <=", value, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribIn(List<Integer> values) {
            addCriterion("contrib in", values, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribNotIn(List<Integer> values) {
            addCriterion("contrib not in", values, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribBetween(Integer value1, Integer value2) {
            addCriterion("contrib between", value1, value2, "contrib");
            return (Criteria) this;
        }

        public Criteria andContribNotBetween(Integer value1, Integer value2) {
            addCriterion("contrib not between", value1, value2, "contrib");
            return (Criteria) this;
        }

        public Criteria andActiveIsNull() {
            addCriterion("active is null");
            return (Criteria) this;
        }

        public Criteria andActiveIsNotNull() {
            addCriterion("active is not null");
            return (Criteria) this;
        }

        public Criteria andActiveEqualTo(Integer value) {
            addCriterion("active =", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotEqualTo(Integer value) {
            addCriterion("active <>", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThan(Integer value) {
            addCriterion("active >", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("active >=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThan(Integer value) {
            addCriterion("active <", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveLessThanOrEqualTo(Integer value) {
            addCriterion("active <=", value, "active");
            return (Criteria) this;
        }

        public Criteria andActiveIn(List<Integer> values) {
            addCriterion("active in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotIn(List<Integer> values) {
            addCriterion("active not in", values, "active");
            return (Criteria) this;
        }

        public Criteria andActiveBetween(Integer value1, Integer value2) {
            addCriterion("active between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andActiveNotBetween(Integer value1, Integer value2) {
            addCriterion("active not between", value1, value2, "active");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveIsNull() {
            addCriterion("thisWeekActive is null");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveIsNotNull() {
            addCriterion("thisWeekActive is not null");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveEqualTo(Integer value) {
            addCriterion("thisWeekActive =", value, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveNotEqualTo(Integer value) {
            addCriterion("thisWeekActive <>", value, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveGreaterThan(Integer value) {
            addCriterion("thisWeekActive >", value, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("thisWeekActive >=", value, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveLessThan(Integer value) {
            addCriterion("thisWeekActive <", value, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveLessThanOrEqualTo(Integer value) {
            addCriterion("thisWeekActive <=", value, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveIn(List<Integer> values) {
            addCriterion("thisWeekActive in", values, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveNotIn(List<Integer> values) {
            addCriterion("thisWeekActive not in", values, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveBetween(Integer value1, Integer value2) {
            addCriterion("thisWeekActive between", value1, value2, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andThisweekactiveNotBetween(Integer value1, Integer value2) {
            addCriterion("thisWeekActive not between", value1, value2, "thisweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveIsNull() {
            addCriterion("lastWeekActive is null");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveIsNotNull() {
            addCriterion("lastWeekActive is not null");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveEqualTo(Integer value) {
            addCriterion("lastWeekActive =", value, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveNotEqualTo(Integer value) {
            addCriterion("lastWeekActive <>", value, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveGreaterThan(Integer value) {
            addCriterion("lastWeekActive >", value, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastWeekActive >=", value, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveLessThan(Integer value) {
            addCriterion("lastWeekActive <", value, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveLessThanOrEqualTo(Integer value) {
            addCriterion("lastWeekActive <=", value, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveIn(List<Integer> values) {
            addCriterion("lastWeekActive in", values, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveNotIn(List<Integer> values) {
            addCriterion("lastWeekActive not in", values, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveBetween(Integer value1, Integer value2) {
            addCriterion("lastWeekActive between", value1, value2, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andLastweekactiveNotBetween(Integer value1, Integer value2) {
            addCriterion("lastWeekActive not between", value1, value2, "lastweekactive");
            return (Criteria) this;
        }

        public Criteria andJointimeIsNull() {
            addCriterion("joinTime is null");
            return (Criteria) this;
        }

        public Criteria andJointimeIsNotNull() {
            addCriterion("joinTime is not null");
            return (Criteria) this;
        }

        public Criteria andJointimeEqualTo(Date value) {
            addCriterion("joinTime =", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeNotEqualTo(Date value) {
            addCriterion("joinTime <>", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeGreaterThan(Date value) {
            addCriterion("joinTime >", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeGreaterThanOrEqualTo(Date value) {
            addCriterion("joinTime >=", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeLessThan(Date value) {
            addCriterion("joinTime <", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeLessThanOrEqualTo(Date value) {
            addCriterion("joinTime <=", value, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeIn(List<Date> values) {
            addCriterion("joinTime in", values, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeNotIn(List<Date> values) {
            addCriterion("joinTime not in", values, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeBetween(Date value1, Date value2) {
            addCriterion("joinTime between", value1, value2, "jointime");
            return (Criteria) this;
        }

        public Criteria andJointimeNotBetween(Date value1, Date value2) {
            addCriterion("joinTime not between", value1, value2, "jointime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_party
     *
     * @mbg.generated do_not_delete_during_merge Sat Jan 11 03:49:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_party
     *
     * @mbg.generated Sat Jan 11 03:49:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}