package org.linlinjava.litemall.db.domain.example;

import java.util.ArrayList;
import java.util.List;

public class PKRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public PKRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdIsNull() {
            addCriterion("pk_chara_id is null");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdIsNotNull() {
            addCriterion("pk_chara_id is not null");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdEqualTo(Integer value) {
            addCriterion("pk_chara_id =", value, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdNotEqualTo(Integer value) {
            addCriterion("pk_chara_id <>", value, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdGreaterThan(Integer value) {
            addCriterion("pk_chara_id >", value, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pk_chara_id >=", value, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdLessThan(Integer value) {
            addCriterion("pk_chara_id <", value, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdLessThanOrEqualTo(Integer value) {
            addCriterion("pk_chara_id <=", value, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdIn(List<Integer> values) {
            addCriterion("pk_chara_id in", values, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdNotIn(List<Integer> values) {
            addCriterion("pk_chara_id not in", values, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdBetween(Integer value1, Integer value2) {
            addCriterion("pk_chara_id between", value1, value2, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andPkCharaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pk_chara_id not between", value1, value2, "pkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdIsNull() {
            addCriterion("be_pk_chara_id is null");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdIsNotNull() {
            addCriterion("be_pk_chara_id is not null");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdEqualTo(Integer value) {
            addCriterion("be_pk_chara_id =", value, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdNotEqualTo(Integer value) {
            addCriterion("be_pk_chara_id <>", value, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdGreaterThan(Integer value) {
            addCriterion("be_pk_chara_id >", value, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("be_pk_chara_id >=", value, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdLessThan(Integer value) {
            addCriterion("be_pk_chara_id <", value, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdLessThanOrEqualTo(Integer value) {
            addCriterion("be_pk_chara_id <=", value, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdIn(List<Integer> values) {
            addCriterion("be_pk_chara_id in", values, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdNotIn(List<Integer> values) {
            addCriterion("be_pk_chara_id not in", values, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdBetween(Integer value1, Integer value2) {
            addCriterion("be_pk_chara_id between", value1, value2, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andBePkCharaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("be_pk_chara_id not between", value1, value2, "bePkCharaId");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNull() {
            addCriterion("server_name is null");
            return (Criteria) this;
        }

        public Criteria andServerNameIsNotNull() {
            addCriterion("server_name is not null");
            return (Criteria) this;
        }

        public Criteria andServerNameEqualTo(String value) {
            addCriterion("server_name =", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotEqualTo(String value) {
            addCriterion("server_name <>", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThan(String value) {
            addCriterion("server_name >", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameGreaterThanOrEqualTo(String value) {
            addCriterion("server_name >=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThan(String value) {
            addCriterion("server_name <", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLessThanOrEqualTo(String value) {
            addCriterion("server_name <=", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameLike(String value) {
            addCriterion("server_name like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotLike(String value) {
            addCriterion("server_name not like", value, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameIn(List<String> values) {
            addCriterion("server_name in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotIn(List<String> values) {
            addCriterion("server_name not in", values, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameBetween(String value1, String value2) {
            addCriterion("server_name between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerNameNotBetween(String value1, String value2) {
            addCriterion("server_name not between", value1, value2, "serverName");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNull() {
            addCriterion("server_id is null");
            return (Criteria) this;
        }

        public Criteria andServerIdIsNotNull() {
            addCriterion("server_id is not null");
            return (Criteria) this;
        }

        public Criteria andServerIdEqualTo(String value) {
            addCriterion("server_id =", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotEqualTo(String value) {
            addCriterion("server_id <>", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThan(String value) {
            addCriterion("server_id >", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdGreaterThanOrEqualTo(String value) {
            addCriterion("server_id >=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThan(String value) {
            addCriterion("server_id <", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLessThanOrEqualTo(String value) {
            addCriterion("server_id <=", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdLike(String value) {
            addCriterion("server_id like", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotLike(String value) {
            addCriterion("server_id not like", value, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdIn(List<String> values) {
            addCriterion("server_id in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotIn(List<String> values) {
            addCriterion("server_id not in", values, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdBetween(String value1, String value2) {
            addCriterion("server_id between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andServerIdNotBetween(String value1, String value2) {
            addCriterion("server_id not between", value1, value2, "serverId");
            return (Criteria) this;
        }

        public Criteria andWinStateIsNull() {
            addCriterion("win_state is null");
            return (Criteria) this;
        }

        public Criteria andWinStateIsNotNull() {
            addCriterion("win_state is not null");
            return (Criteria) this;
        }

        public Criteria andWinStateEqualTo(Boolean value) {
            addCriterion("win_state =", value, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateNotEqualTo(Boolean value) {
            addCriterion("win_state <>", value, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateGreaterThan(Boolean value) {
            addCriterion("win_state >", value, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("win_state >=", value, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateLessThan(Boolean value) {
            addCriterion("win_state <", value, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateLessThanOrEqualTo(Boolean value) {
            addCriterion("win_state <=", value, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateIn(List<Boolean> values) {
            addCriterion("win_state in", values, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateNotIn(List<Boolean> values) {
            addCriterion("win_state not in", values, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateBetween(Boolean value1, Boolean value2) {
            addCriterion("win_state between", value1, value2, "winState");
            return (Criteria) this;
        }

        public Criteria andWinStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("win_state not between", value1, value2, "winState");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(String value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(String value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(String value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(String value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(String value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(String value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLike(String value) {
            addCriterion("add_time like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotLike(String value) {
            addCriterion("add_time not like", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<String> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<String> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(String value1, String value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(String value1, String value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pk_record
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 05 22:20:54 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pk_record
     *
     * @mbg.generated Wed Feb 05 22:20:54 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}